version: "3.9"
services:
  artemis:
    image: activemq-artemis:latest
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "logs-database"
  log-stats:
    image: log-stats:latest
    deploy:
      replicas: 2
    depends_on:
      - mysql
      - artemis
  log-collector:
    image: log-collector:latest
    ports:
      - 8080:8080
    depends_on:
      - log-stats
  management-console:
    image: management-console:latest
    ports:
      - 80:8080
    depends_on:
      - mysql
      - artemis
